spring:
    application:
        name: security-module-oauth2
        
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/emaildb"
        username: "root"
        password: "1234"
    
        
       
                   
